services:
  db:
    container_name: armut_test_db
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: npm start
    volumes:
      - ./app:/code
    ports:
      - "3000:3000"
    environment:
      DB_URI: "mongodb://armut_test_db:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
    depends_on:
      - db